In [26]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [28]:
import os

for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for file in files:
        if file.endswith('.csv'):
            print(os.path.join(root, file))

/content/drive/MyDrive/Medicare_Physician_Other_Practitioners_by_Provider_and_Service_2024.csv
/content/drive/MyDrive/cms_cleaned.csv
/content/drive/MyDrive/cms_mysql_ready.csv

In [29]:
import pandas as pd

path = "/content/drive/MyDrive/Medicare_Physician_Other_Practitioners_by_Provider_and_Service_2024.csv"

df = pd.read_csv(path, nrows=5)

print(df.columns.tolist())

['Rndrng_NPI', 'Rndrng_Prvdr_Last_Org_Name', 'Rndrng_Prvdr_First_Name', 'Rndrng_Prvdr_MI', 'Rndrng_Prvdr_Crdntls', 'Rndrng_Prvdr_Ent_Cd', 'Rndrng_Prvdr_St1', 'Rndrng_Prvdr_St2', 'Rndrng_Prvdr_City', 'Rndrng_Prvdr_State_Abrvtn', 'Rndrng_Prvdr_State_FIPS', 'Rndrng_Prvdr_Zip5', 'Rndrng_Prvdr_RUCA', 'Rndrng_Prvdr_RUCA_Desc', 'Rndrng_Prvdr_Cntry', 'Rndrng_Prvdr_Type', 'Rndrng_Prvdr_Mdcr_Prtcptg_Ind', 'HCPCS_Cd', 'HCPCS_Desc', 'HCPCS_Drug_Ind', 'Place_Of_Srvc', 'Tot_Benes', 'Tot_Srvcs', 'Tot_Bene_Day_Srvcs', 'Avg_Sbmtd_Chrg', 'Avg_Mdcr_Alowd_Amt', 'Avg_Mdcr_Pymt_Amt', 'Avg_Mdcr_Stdzd_Amt']

In [30]:
import pandas as pd

path = "/content/drive/MyDrive/Medicare_Physician_Other_Practitioners_by_Provider_and_Service_2024.csv"

chunks = []
chunk_size = 100000

for chunk in pd.read_csv(path, chunksize=chunk_size):
    chunks.append(chunk.sample(frac=0.05, random_state=42))

sample = pd.concat(chunks)

print(sample.shape)

sample.to_csv("cms_sample.csv", index=False)

/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):
/tmp/ipykernel_1637/2962830893.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(path, chunksize=chunk_size):

(489084, 28)

In [14]:
print(sample.shape)

(489084, 28)

In [15]:
sample.head()

,Rndrng_NPI,Rndrng_Prvdr_Last_Org_Name,Rndrng_Prvdr_First_Name,Rndrng_Prvdr_MI,Rndrng_Prvdr_Crdntls,Rndrng_Prvdr_Ent_Cd,Rndrng_Prvdr_St1,Rndrng_Prvdr_St2,Rndrng_Prvdr_City,Rndrng_Prvdr_State_Abrvtn,...,HCPCS_Desc,HCPCS_Drug_Ind,Place_Of_Srvc,Tot_Benes,Tot_Srvcs,Tot_Bene_Day_Srvcs,Avg_Sbmtd_Chrg,Avg_Mdcr_Alowd_Amt,Avg_Mdcr_Pymt_Amt,Avg_Mdcr_Stdzd_Amt
75721,1003865585,Mayer,Robert,S,M.D.,I,600 N Wolfe St,NaN,Baltimore,MD,...,Maintenance of spinal canal or brain drug infu...,N,O,16,43.0,43,331.000000,116.148837,92.133023,86.017674
80184,1003878448,Johnson,Kevin,K,MD,I,501 E Hampden Ave,NaN,Englewood,CO,...,Ct scan of abdomen and pelvis with contrast,N,O,31,31.0,31,1102.916129,273.328710,216.565484,198.862258
19864,1003137613,Peterson,Phillip,R,M.D.,I,One Hospital Drive,NaN,Lewisburg,PA,...,Emergency department visit with moderate level...,N,F,36,36.0,36,260.000000,115.537222,81.747222,83.420000
76699,1003868654,Lintner,Scott,A,MD,I,8450 Northwest Blvd,NaN,Indianapolis,IN,...,Shaving of part of shoulder bone and repair of...,N,F,15,15.0,15,4191.000000,153.398000,122.320000,132.656000
92991,1003939117,Duncan,Graham,S,MD,I,940 Golf House Rd E,NaN,Stoney Creek,NC,...,"Annual wellness visit, includes a personalized...",N,O,118,118.0,118,298.076271,120.489153,120.489153,127.144576

In [16]:
sample.info()

<class 'pandas.core.frame.DataFrame'>
Index: 489084 entries, 75721 to 9720770
Data columns (total 28 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Rndrng_NPI                     489084 non-null  int64
 1   Rndrng_Prvdr_Last_Org_Name     489084 non-null  object
 2   Rndrng_Prvdr_First_Name        465540 non-null  object
 3   Rndrng_Prvdr_MI                316022 non-null  object
 4   Rndrng_Prvdr_Crdntls           435211 non-null  object
 5   Rndrng_Prvdr_Ent_Cd            489084 non-null  object
 6   Rndrng_Prvdr_St1               489084 non-null  object
 7   Rndrng_Prvdr_St2               107116 non-null  object
 8   Rndrng_Prvdr_City              489084 non-null  object
 9   Rndrng_Prvdr_State_Abrvtn      489084 non-null  object
 10  Rndrng_Prvdr_State_FIPS        489084 non-null  object
 11  Rndrng_Prvdr_Zip5              489084 non-null  object
 12  Rndrng_Prvdr_RUCA              488828 non-null  float64
 13  Rndrng_Prvdr_RUCA_Desc         488828 non-null  object
 14  Rndrng_Prvdr_Cntry             489084 non-null  object
 15  Rndrng_Prvdr_Type              489084 non-null  object
 16  Rndrng_Prvdr_Mdcr_Prtcptg_Ind  489084 non-null  object
 17  HCPCS_Cd                       489084 non-null  object
 18  HCPCS_Desc                     489084 non-null  object
 19  HCPCS_Drug_Ind                 489084 non-null  object
 20  Place_Of_Srvc                  489084 non-null  object
 21  Tot_Benes                      489084 non-null  int64
 22  Tot_Srvcs                      489084 non-null  float64
 23  Tot_Bene_Day_Srvcs             489084 non-null  int64
 24  Avg_Sbmtd_Chrg                 489084 non-null  float64
 25  Avg_Mdcr_Alowd_Amt             489084 non-null  float64
 26  Avg_Mdcr_Pymt_Amt              489084 non-null  float64
 27  Avg_Mdcr_Stdzd_Amt             489084 non-null  float64
dtypes: float64(6), int64(3), object(19)
memory usage: 108.2+ MB

In [17]:
sample.describe()

,Rndrng_NPI,Rndrng_Prvdr_RUCA,Tot_Benes,Tot_Srvcs,Tot_Bene_Day_Srvcs,Avg_Sbmtd_Chrg,Avg_Mdcr_Alowd_Amt,Avg_Mdcr_Pymt_Amt,Avg_Mdcr_Stdzd_Amt
count,4.890840e+05,488828.000000,489084.000000,4.890840e+05,489084.000000,489084.000000,489084.000000,489084.000000,489084.000000
mean,1.499303e+09,1.547098,83.864393,2.861453e+02,135.642039,430.813420,106.185652,82.861613,82.337744
std,2.877077e+08,3.338305,1112.339742,7.458550e+03,1801.279956,1500.533256,325.623561,259.834329,260.162511
min,1.003001e+09,1.000000,11.000000,1.100000e+01,11.000000,0.000215,0.000000,0.000000,0.000000
25%,1.245913e+09,1.000000,17.000000,2.100000e+01,20.000000,74.000000,25.506730,19.716023,19.543806
50%,1.497935e+09,1.000000,32.000000,4.300000e+01,40.000000,180.000000,71.719235,52.658110,52.813631
75%,1.740786e+09,1.000000,72.000000,1.190000e+02,106.000000,367.540000,121.352294,91.144318,90.925222
max,1.993000e+09,99.000000,366441.000000,4.371834e+06,683703.000000,99999.000000,30464.635862,24272.637586,20115.995333

In [18]:
sample.isnull().sum()

Rndrng_NPI                            0
Rndrng_Prvdr_Last_Org_Name            0
Rndrng_Prvdr_First_Name           23544
Rndrng_Prvdr_MI                  173062
Rndrng_Prvdr_Crdntls              53873
Rndrng_Prvdr_Ent_Cd                   0
Rndrng_Prvdr_St1                      0
Rndrng_Prvdr_St2                 381968
Rndrng_Prvdr_City                     0
Rndrng_Prvdr_State_Abrvtn             0
Rndrng_Prvdr_State_FIPS               0
Rndrng_Prvdr_Zip5                     0
Rndrng_Prvdr_RUCA                   256
Rndrng_Prvdr_RUCA_Desc              256
Rndrng_Prvdr_Cntry                    0
Rndrng_Prvdr_Type                     0
Rndrng_Prvdr_Mdcr_Prtcptg_Ind         0
HCPCS_Cd                              0
HCPCS_Desc                            0
HCPCS_Drug_Ind                        0
Place_Of_Srvc                         0
Tot_Benes                             0
Tot_Srvcs                             0
Tot_Bene_Day_Srvcs                    0
Avg_Sbmtd_Chrg                        0
Avg_Mdcr_Alowd_Amt                    0
Avg_Mdcr_Pymt_Amt                     0
Avg_Mdcr_Stdzd_Amt                    0
dtype: int64

In [19]:
sample.duplicated().sum()

np.int64(0)

In [21]:
sample = sample.drop(columns=["Rndrng_Prvdr_St2"])
sample = sample.drop(columns=["Rndrng_Prvdr_MI"])

In [23]:
sample.to_csv(
    "/content/drive/MyDrive/cms_cleaned.csv",
    index=False
)

In [24]:
print(sample.shape)

(489084, 26)

In [25]:
sample.to_csv(
    "/content/drive/MyDrive/cms_mysql_ready.csv",
    index=False,
    encoding="utf-8",
    lineterminator="\n"
)

print(sample.shape)
print("cms_mysql_ready.csv saved successfully")

(489084, 26)
cms_mysql_ready.csv saved successfully